<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Using R for Data Analysis and Graphics - 3&nbsp; Multiple Linear Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./GLMandA.html" rel="next">
<link href="./graphs.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Multiple Linear Regression</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Using R for Data Analysis and Graphics</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Preface</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">An overview of the R system</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./graphs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Base R Graphics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reg.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Multiple Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./GLMandA.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Generalized Linear and Additive Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ts.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Regular Time Series in R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./trees.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Tree-based models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mva.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Multivariate Methods</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Multi-Level Models and Repeated Measures Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#linear-model-objects" id="toc-linear-model-objects" class="nav-link active" data-scroll-target="#linear-model-objects"><span class="toc-section-number">3.1</span>  Linear model objects</a></li>
  <li><a href="#model-formulae-and-the-x-matrix" id="toc-model-formulae-and-the-x-matrix" class="nav-link" data-scroll-target="#model-formulae-and-the-x-matrix"><span class="toc-section-number">3.2</span>  Model Formulae, and the <code>X</code> Matrix</a>
  <ul class="collapse">
  <li><a href="#model-formulae-more-generally" id="toc-model-formulae-more-generally" class="nav-link" data-scroll-target="#model-formulae-more-generally"><span class="toc-section-number">3.2.1</span>  Model formulae more generally</a></li>
  <li><a href="#manipulating-model-formulae" id="toc-manipulating-model-formulae" class="nav-link" data-scroll-target="#manipulating-model-formulae"><span class="toc-section-number">3.2.2</span>  *Manipulating Model Formulae</a></li>
  </ul></li>
  <li><a href="#multiple-linear-regression-models" id="toc-multiple-linear-regression-models" class="nav-link" data-scroll-target="#multiple-linear-regression-models"><span class="toc-section-number">3.3</span>  Multiple Linear Regression Models</a>
  <ul class="collapse">
  <li><a href="#the-data-frame-rubber" id="toc-the-data-frame-rubber" class="nav-link" data-scroll-target="#the-data-frame-rubber"><span class="toc-section-number">3.3.1</span>  The data frame Rubber</a></li>
  <li><a href="#weights-of-books" id="toc-weights-of-books" class="nav-link" data-scroll-target="#weights-of-books"><span class="toc-section-number">3.3.2</span>  Weights of Books</a></li>
  </ul></li>
  <li><a href="#polynomial-and-spline-regression" id="toc-polynomial-and-spline-regression" class="nav-link" data-scroll-target="#polynomial-and-spline-regression"><span class="toc-section-number">3.4</span>  Polynomial and Spline Regression</a>
  <ul class="collapse">
  <li><a href="#spline-terms-in-linear-models" id="toc-spline-terms-in-linear-models" class="nav-link" data-scroll-target="#spline-terms-in-linear-models"><span class="toc-section-number">3.4.1</span>  Spline Terms in Linear Models</a></li>
  </ul></li>
  <li><a href="#sec-lines2" id="toc-sec-lines2" class="nav-link" data-scroll-target="#sec-lines2"><span class="toc-section-number">3.5</span>  Using Factors in R Models</a>
  <ul class="collapse">
  <li><a href="#other-choices-of-contrasts" id="toc-other-choices-of-contrasts" class="nav-link" data-scroll-target="#other-choices-of-contrasts"><span class="toc-section-number">3.5.1</span>  Other Choices of Contrasts</a></li>
  </ul></li>
  <li><a href="#multiple-lines-different-regression-lines-for-different-species" id="toc-multiple-lines-different-regression-lines-for-different-species" class="nav-link" data-scroll-target="#multiple-lines-different-regression-lines-for-different-species"><span class="toc-section-number">3.6</span>  Multiple Lines – Different Regression Lines for Different Species</a></li>
  <li><a href="#aov-models-analysis-of-variance" id="toc-aov-models-analysis-of-variance" class="nav-link" data-scroll-target="#aov-models-analysis-of-variance"><span class="toc-section-number">3.7</span>  aov models (Analysis of Variance)</a>
  <ul class="collapse">
  <li><a href="#plant-growth-example" id="toc-plant-growth-example" class="nav-link" data-scroll-target="#plant-growth-example"><span class="toc-section-number">3.7.1</span>  Plant Growth Example</a></li>
  <li><a href="#dataset-masscabbages-run-code-to-get-output" id="toc-dataset-masscabbages-run-code-to-get-output" class="nav-link" data-scroll-target="#dataset-masscabbages-run-code-to-get-output"><span class="toc-section-number">3.7.2</span>  Dataset <code>MASS::cabbages</code> (Run code to get output)</a></li>
  </ul></li>
  <li><a href="#sec-errorAOV" id="toc-sec-errorAOV" class="nav-link" data-scroll-target="#sec-errorAOV"><span class="toc-section-number">3.8</span>  Shading of Kiwifruit Vines</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="toc-section-number">3.9</span>  Exercises</a></li>
  <li><a href="#references-and-reading" id="toc-references-and-reading" class="nav-link" data-scroll-target="#references-and-reading"><span class="toc-section-number">3.10</span>  References and reading</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Multiple Linear Regression</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="linear-model-objects" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="linear-model-objects"><span class="header-section-number">3.1</span> Linear model objects</h2>
<p>We begin with the straight line regression example that appeared earlier, in <a href="basics.html#sec-typing"><span>Section&nbsp;1.1</span></a>. Look ahead to <a href="#fig-fig21">Figure&nbsp;<span>3.1</span></a>, where a regression line has been added.</p>
<p>The code for the regression calculation is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>elastic.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(distance <span class="sc">~</span> stretch, <span class="at">data=</span>DAAG<span class="sc">::</span>elasticband)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The object <code>distance ~ stretch</code> is a <em>model formula</em>, used to specify details of the model that is to be fitted. Other model formulae will appear in the course of this chapter.</p>
<div class="cell">

</div>
<div class="cell" data-fig.asp="1.1">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>elasticband <span class="ot">&lt;-</span> DAAG<span class="sc">::</span>elasticband</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(distance <span class="sc">~</span> stretch, <span class="at">data=</span>DAAG<span class="sc">::</span>elasticband)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(elastic.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-fig21" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="reg_files/figure-html/fig-fig21-1.png" class="img-fluid figure-img" style="width:40.0%"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;3.1: Plot of distance versus stretch for the elastic band data, with fitted least squares line</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The output from the regression is an <code>lm</code> object, which we have called <code>elastic.lm</code>. Now examine a summary of the regression results. Notice that the output documents the model formula that was used:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(elastic.lm, <span class="at">digits=</span><span class="dv">4</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>Call<span class="sc">:</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(<span class="at">formula =</span> distance <span class="sc">~</span> stretch, <span class="at">data =</span> DAAG<span class="sc">::</span>elasticband)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>Residuals<span class="sc">:</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>       <span class="dv">1</span>        <span class="dv">2</span>        <span class="dv">3</span>        <span class="dv">4</span>        <span class="dv">5</span>        <span class="dv">6</span>        <span class="dv">7</span> </span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="fl">2.1071</span>  <span class="sc">-</span><span class="fl">0.3214</span>  <span class="fl">18.0000</span>   <span class="fl">1.8929</span> <span class="sc">-</span><span class="fl">27.7857</span>  <span class="fl">13.3214</span>  <span class="sc">-</span><span class="fl">7.2143</span> </span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>Coefficients<span class="sc">:</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>            Estimate Std. Error t value <span class="fu">Pr</span>(<span class="sc">&gt;</span><span class="er">|</span>t<span class="sc">|</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>(Intercept)  <span class="sc">-</span><span class="fl">63.571</span>     <span class="fl">74.332</span>  <span class="sc">-</span><span class="fl">0.855</span>   <span class="fl">0.4315</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>stretch        <span class="fl">4.554</span>      <span class="fl">1.543</span>   <span class="fl">2.951</span>   <span class="fl">0.0319</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>Residual standard error<span class="sc">:</span> <span class="fl">16.33</span> on <span class="dv">5</span> degrees of freedom</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>Multiple R<span class="sc">-</span>squared<span class="sc">:</span>  <span class="fl">0.6352</span>,    Adjusted R<span class="sc">-</span>squared<span class="sc">:</span>  <span class="fl">0.5622</span> </span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>F<span class="sc">-</span>statistic<span class="sc">:</span> <span class="fl">8.706</span> on <span class="dv">1</span> and <span class="dv">5</span> DF,  p<span class="sc">-</span>value<span class="sc">:</span> <span class="fl">0.03186</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>An <code>lm</code> object is a list of named elements. Names of <code>elastic.lm</code> are:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(elastic.lm)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a> [<span class="dv">1</span>] <span class="st">"coefficients"</span>  <span class="st">"residuals"</span>     <span class="st">"effects"</span>       <span class="st">"rank"</span>         </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a> [<span class="dv">5</span>] <span class="st">"fitted.values"</span> <span class="st">"assign"</span>        <span class="st">"qr"</span>            <span class="st">"df.residual"</span>  </span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a> [<span class="dv">9</span>] <span class="st">"xlevels"</span>       <span class="st">"call"</span>          <span class="st">"terms"</span>         <span class="st">"model"</span>        </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>A number of functions are available for extracting information that might be required from the list. This is or most purposes preferable to extracting elements from the list directly. Examples are:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(elastic.lm)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>(Intercept)     stretch </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a> <span class="sc">-</span><span class="fl">63.571429</span>    <span class="fl">4.553571</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The function most often used to inspect regression output is <code>summary()</code>. It extracts the information that users are most likely to want. In section 5.1, we had</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(elastic.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>There is a plot method for <em>lm</em> objects that gives the diagnostic information shown in <a href="#fig-fig22">Figure&nbsp;<span>3.2</span></a>.</p>
<div class="cell">

</div>
<div class="cell" data-fig.asp="0.28">
<div class="cell-output-display">
<div id="fig-fig22" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="reg_files/figure-html/fig-fig22-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;3.2: Diagnostic plot of lm object, obtained by <code>plot(elastic.lm)</code>.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>To get <a href="#fig-fig22">Figure&nbsp;<span>3.2</span></a>, type:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>opar <span class="ot">&lt;-</span> <span class="fu">par</span>(<span class="at">mar=</span><span class="fu">c</span>(<span class="fl">4.6</span>,<span class="fl">3.6</span>,<span class="fl">2.1</span>,<span class="fl">2.1</span>), <span class="at">mgp=</span><span class="fu">c</span>(<span class="dv">2</span>,.<span class="dv">5</span>,<span class="dv">0</span>), <span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">4</span>)) </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(elastic.lm)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(opar)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>By default the first, second and fourth plot use the row names to identify the three most extreme residuals. [If explicit row names are not given for the data frame, then the row numbers are used.]</p>
</section>
<section id="model-formulae-and-the-x-matrix" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="model-formulae-and-the-x-matrix"><span class="header-section-number">3.2</span> Model Formulae, and the <code>X</code> Matrix</h2>
<p>The model formula for the elastic band example was distance ~ stretch . The model formula is a recipe for setting up the calculations. All the calculations described in this chapter involve the use of an model matrix or <code>X</code> matrix, and a vector <code>y</code> of values of the dependent variable. For some of the examples we discuss later, it helps to know what the <code>X</code> matrix looks like. Details for the elastic band example follow. The <code>X</code> matrix, with the <code>y</code>-vector alongside, is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="fu">model.matrix</span>(elastic.lm), <span class="at">distance=</span>elasticband<span class="sc">$</span>distance)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  (Intercept) stretch distance</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span>           <span class="dv">1</span>      <span class="dv">46</span>      <span class="dv">148</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span>           <span class="dv">1</span>      <span class="dv">54</span>      <span class="dv">182</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="dv">3</span>           <span class="dv">1</span>      <span class="dv">48</span>      <span class="dv">173</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="dv">4</span>           <span class="dv">1</span>      <span class="dv">50</span>      <span class="dv">166</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="dv">5</span>           <span class="dv">1</span>      <span class="dv">44</span>      <span class="dv">109</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="dv">6</span>           <span class="dv">1</span>      <span class="dv">42</span>      <span class="dv">141</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="dv">7</span>           <span class="dv">1</span>      <span class="dv">52</span>      <span class="dv">166</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The model matrix relates to the part of the model that appears to the right of the equals sign. The straight line model is <span class="math inline">\(y = a + b x + \mbox{residual}\)</span>, which we write as <span class="math display">\[ y = a \times 1 + b \times x + \mbox{residual}\]</span> The following are the fitted values and residuals that we get with the estimates of <code>a</code> (= -63.6) and <code>b</code> ( = 4.55) from the least squares regression</p>
<table class="table">
<colgroup>
<col style="width: 4%">
<col style="width: 30%">
<col style="width: 18%">
<col style="width: 23%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>1</th>
<th>Stretch (mm)</th>
<th>(Fitted)</th>
<th>(Observed)</th>
<th>(Residual)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(-63.6 \times\)</span></td>
<td><span class="math inline">\(4.55 \times\)</span></td>
<td><span class="math inline">\(-63.6 + 4.55 \times \mbox{Stretch}\)</span></td>
<td><span class="math inline">\(\mbox{Distance (mm)}\)</span></td>
<td><span class="math inline">\(\mbox{Observed – Fitted}\)</span></td>
</tr>
<tr class="even">
<td>1</td>
<td>46</td>
<td><span class="math inline">\(-63.6 + 4.55 \times 46 = 145.7\)</span></td>
<td>148</td>
<td>148-145.7 = 2.3</td>
</tr>
<tr class="odd">
<td>1</td>
<td>54</td>
<td><span class="math inline">\(-63.6 + 4.55 \times 54 = 182.1\)</span></td>
<td>182</td>
<td>182-182.1 = -0.1</td>
</tr>
<tr class="even">
<td>1</td>
<td>48</td>
<td><span class="math inline">\(-63.6 + 4.55 \times 48 = 154.8\)</span></td>
<td>173</td>
<td>173-154.8 = 18.2</td>
</tr>
<tr class="odd">
<td>1</td>
<td>50</td>
<td><span class="math inline">\(-63.6 + 4.55 \times 50 = 163.9\)</span></td>
<td>166</td>
<td>166-163.9 = 2.1</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
</tbody>
</table>
<p>The symbol <span class="math inline">\(\hat{y}\)</span> [pronounced y-hat] is commonly used fot fitted values of the variable <span class="math inline">\(y\)</span>.</p>
<p>We might alternatively fit the simpler (no intercept) model. For this we have <span class="math display">\[
y = x \times b + e
\]</span> where <span class="math inline">\(e\)</span> is a random variable with mean 0. The <code>X</code> matrix then consists of a single column, holding the values of <code>x</code>.</p>
<section id="model-formulae-more-generally" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="model-formulae-more-generally"><span class="header-section-number">3.2.1</span> Model formulae more generally</h3>
<p>Model formulae take forms such as:</p>
<pre><code>y ~ x+z             # Fit y as a linear combination of x and z
y~x + fac + fac:x 
  # If fac is a factor and x is a variable, fac:x allows 
  # a different slope for each different level of fac.</code></pre>
<p>Model formulae are widely used to set up most of the model calculations in R.<br>
Notice the similarity between model formulae and the formulae that can be used for specifying plots. Thus, recall the graph formula for a <code>coplot</code> that gives a plot of <code>y</code> against <code>x</code> for each different combination of levels of <code>fac1</code> (across the page) and <code>fac2</code> (up the page) is:</p>
<pre><code>y ~ x | fac1+fac2</code></pre>
</section>
<section id="manipulating-model-formulae" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="manipulating-model-formulae"><span class="header-section-number">3.2.2</span> *Manipulating Model Formulae</h3>
<p>Model formulae can be assigned, e.g.&nbsp;</p>
<pre><code>formyxz &lt;- formula(y~x+z)</code></pre>
<p>or</p>
<pre><code>formyxz &lt;- formula(“y~x+z”)</code></pre>
<p>The argument to <code>formula()</code> can, as just demonstrated, be a text string. This makes it straightforward to paste the argument together from components that are stored in text strings. For example</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(elasticband)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>[<span class="dv">1</span>] <span class="st">"stretch"</span>  <span class="st">"distance"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>nam <span class="ot">&lt;-</span> <span class="fu">names</span>(elasticband)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>formds <span class="ot">&lt;-</span> <span class="fu">formula</span>(<span class="fu">paste</span>(nam[<span class="dv">1</span>],<span class="st">"~"</span>,nam[<span class="dv">2</span>]))</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(formds, <span class="at">data=</span>elasticband)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>Call<span class="sc">:</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(<span class="at">formula =</span> formds, <span class="at">data =</span> elasticband)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>Coefficients<span class="sc">:</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>(Intercept)     distance  </span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>    <span class="fl">26.3780</span>       <span class="fl">0.1395</span>  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that graphics formulae can be manipulated in exactly the same way as model formulae.</p>
</section>
</section>
<section id="multiple-linear-regression-models" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="multiple-linear-regression-models"><span class="header-section-number">3.3</span> Multiple Linear Regression Models</h2>
<section id="the-data-frame-rubber" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="the-data-frame-rubber"><span class="header-section-number">3.3.1</span> The data frame Rubber</h3>
<p>The data set <code>MASS::Rubber</code> is from the accelerated testing of tyre rubber. The variables are <code>loss</code> (the abrasion loss in gm/hr), <code>hard</code> (hardness in ‘Shore’ units), and <code>tens</code> (tensile strength in kg/sq m).<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> <a href="#fig-fig23">Figure&nbsp;<span>3.3</span></a> shows a scatterplot matrix for the variables:</p>
<div class="cell">

</div>
<div class="cell" data-fig.asp="1">
<div class="cell-output-display">
<div id="fig-fig23" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="reg_files/figure-html/fig-fig23-1.png" class="img-fluid figure-img" style="width:70.0%"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;3.3: Scatterplot matrix for the data frame <code>MASS::Rubber</code></figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Code is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(MASS<span class="sc">::</span>Rubber)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>There is a negative correlation between <code>loss</code> and <code>hard</code>.<br>
We proceed to regress <code>loss</code> on <code>hard</code> and <code>tens</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>Rubber.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(loss<span class="sc">~</span>hard<span class="sc">+</span>tens, <span class="at">data=</span>MASS<span class="sc">::</span>Rubber)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Rubber.lm, <span class="at">digits=</span><span class="dv">3</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>Call<span class="sc">:</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(<span class="at">formula =</span> loss <span class="sc">~</span> hard <span class="sc">+</span> tens, <span class="at">data =</span> MASS<span class="sc">::</span>Rubber)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>Residuals<span class="sc">:</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    Min      1Q  Median      3Q     Max </span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">79.385</span> <span class="sc">-</span><span class="fl">14.608</span>   <span class="fl">3.816</span>  <span class="fl">19.755</span>  <span class="fl">65.981</span> </span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>Coefficients<span class="sc">:</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>            Estimate Std. Error t value <span class="fu">Pr</span>(<span class="sc">&gt;</span><span class="er">|</span>t<span class="sc">|</span>)</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>(Intercept) <span class="fl">885.1611</span>    <span class="fl">61.7516</span>  <span class="fl">14.334</span> <span class="fl">3.84e-14</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>hard         <span class="sc">-</span><span class="fl">6.5708</span>     <span class="fl">0.5832</span> <span class="sc">-</span><span class="fl">11.267</span> <span class="fl">1.03e-11</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>tens         <span class="sc">-</span><span class="fl">1.3743</span>     <span class="fl">0.1943</span>  <span class="sc">-</span><span class="fl">7.073</span> <span class="fl">1.32e-07</span></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>Residual standard error<span class="sc">:</span> <span class="fl">36.49</span> on <span class="dv">27</span> degrees of freedom</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>Multiple R<span class="sc">-</span>squared<span class="sc">:</span>  <span class="fl">0.8402</span>,    Adjusted R<span class="sc">-</span>squared<span class="sc">:</span>  <span class="fl">0.8284</span> </span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>F<span class="sc">-</span>statistic<span class="sc">:</span>    <span class="dv">71</span> on <span class="dv">2</span> and <span class="dv">27</span> DF,  p<span class="sc">-</span>value<span class="sc">:</span> <span class="fl">1.767e-11</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In addition to the use of <code>plot()</code> with <code>lm</code> objects, note the use of <code>termplot()</code>.</p>
<div class="cell">

</div>
<div class="cell" data-fig.asp="0.55">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">termplot</span>(Rubber.lm, <span class="at">partial=</span><span class="cn">TRUE</span>, <span class="at">smooth=</span>panel.smooth)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-fig24" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="reg_files/figure-html/fig-fig24-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;3.4: Plot, obtained with termplot(), showing the contribution of each of the two terms in the model, at the mean of the contributions for the other term. A smooth curve has, in each panel, been fitted through the partial residuals. There is a clear suggestion that, at the upper end of the range, the response is not linear with tensile strength.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Figure @ref(fig:fig24) used the following code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">termplot</span>(Rubber.lm, <span class="at">partial=</span><span class="cn">TRUE</span>, <span class="at">smooth=</span>panel.smooth)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This plot raises interesting questions.</p>
</section>
<section id="weights-of-books" class="level3" data-number="3.3.2">
<h3 data-number="3.3.2" class="anchored" data-anchor-id="weights-of-books"><span class="header-section-number">3.3.2</span> Weights of Books</h3>
<p>The books to which the data in the data set <code>DAAG::oddbooks</code> refer were chosen to cover a wide range of weight to height ratios. The use of the data to fit regression models illustrates how biases that affect the collection of observational data can skew results.</p>
<div class="cell">

</div>
<div class="cell" data-fig.asp="1">
<div class="cell-output-display">
<div id="fig-fig25" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="reg_files/figure-html/fig-fig25-1.png" class="img-fluid figure-img" style="width:72.0%"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;3.5: Scatterplot matrix for the data frame <code>DAAG::oddbooks</code></figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Code is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(DAAG<span class="sc">::</span>oddbooks)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The correlations between <code>thick</code>, <code>height</code> and <code>width</code> are so strong that if one tries to use more than one of them as a explanatory variables, the coefficients are ill-determined. They contain very similar information, as is evident from the scatterplot matrix. The regressions on height and width give plausible results, while the coefficient of the regression on thick is entirely an artefact of the way that the books were selected.</p>
<p>The design of the data collection really is important for the interpretation of coefficients from a regression equation. Even where regression equations from observational data appear to work well for predictive purposes, the individual coefficients may be misleading. This is more than an academic issue, as the analyses in Lalonde (1986) demonstrate. They had data from experimental “treatment” and “control” groups, and also from two comparable non-experimental “controls”. The regression estimate of the treatment effect, when comparison was with one of the non-experimental controls, was statistically significant but with the wrong sign! The regression should be fitted only to that part of the data where values of the covariates overlap substantially. Dehejia and Wahba demonstrate the use of scores (“propensities”) to identify subsets that are defensibly comparable. The propensity is then the only covariate in the equation that estimates the treatment effect. It is impossible to be sure that any method is giving the right answer.</p>
<p>Assuming a uniform density, the geometry suggests <span class="math display">\[
\mbox{weight} = \mbox{density} \times \mbox{thick}  \times \mbox{height}  \times \mbox{breadth}
\]</span> On a logarithmic scale, this transforms to <span class="math display">\[
\begin{aligned}
\log(\mbox{weight}) &amp;= \log(\mbox{density}) + \log(\mbox{thick})  + \log(\mbox{height})  + \log(\mbox{breadth})\\
&amp;= \log(\mbox{density}) + \log(\mbox{volume})
\end{aligned}
\]</span></p>
<p>The following ignores what the geometry suggests</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>logbooks <span class="ot">&lt;-</span> <span class="fu">log</span>(DAAG<span class="sc">::</span>oddbooks) <span class="co"># We might expect weight to be</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>                                <span class="co"># proportional to thick * height * width</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Regress log(weight) on log(thick) + log(height) + log(breadth)</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>logbooks.lm3<span class="ot">&lt;-</span><span class="fu">lm</span>(weight<span class="sc">~</span>thick<span class="sc">+</span>height<span class="sc">+</span>breadth,<span class="at">data=</span>logbooks)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># NB: `weight` is really `log(weight)`,</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># and similarly for other variables</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">capture.output</span>(<span class="fu">summary</span>(logbooks.lm3, <span class="at">digits=</span><span class="dv">2</span>))[<span class="sc">-</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>)], <span class="at">sep=</span><span class="st">'</span><span class="sc">\n</span><span class="st">'</span>)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>Coefficients<span class="sc">:</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>            Estimate Std. Error t value <span class="fu">Pr</span>(<span class="sc">&gt;</span><span class="er">|</span>t<span class="sc">|</span>)</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>(Intercept)  <span class="sc">-</span><span class="fl">0.7191</span>     <span class="fl">3.2162</span>  <span class="sc">-</span><span class="fl">0.224</span>    <span class="fl">0.829</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>thick         <span class="fl">0.4648</span>     <span class="fl">0.4344</span>   <span class="fl">1.070</span>    <span class="fl">0.316</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>height        <span class="fl">0.1537</span>     <span class="fl">1.2734</span>   <span class="fl">0.121</span>    <span class="fl">0.907</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>breadth       <span class="fl">1.8772</span>     <span class="fl">1.0696</span>   <span class="fl">1.755</span>    <span class="fl">0.117</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>Residual standard error<span class="sc">:</span> <span class="fl">0.1611</span> on <span class="dv">8</span> degrees of freedom</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>Multiple R<span class="sc">-</span>squared<span class="sc">:</span>  <span class="fl">0.8978</span>,    Adjusted R<span class="sc">-</span>squared<span class="sc">:</span>  <span class="fl">0.8595</span> </span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>F<span class="sc">-</span>statistic<span class="sc">:</span> <span class="fl">23.43</span> on <span class="dv">3</span> and <span class="dv">8</span> DF,  p<span class="sc">-</span>value<span class="sc">:</span> <span class="fl">0.000257</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Notice that all the coefficients are at the level of statistical error, but even so the overall fit (<span class="math inline">\(p\)</span>=0.000257) is clearly good.</p>
<p>Now regress on <span class="math inline">\(\mbox{logVolume}\)</span> = <span class="math inline">\(\log(\mbox{volume})\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Regress log(weight) on log(thick) + log(height) + log(breadth)</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>logVolume <span class="ot">&lt;-</span> <span class="fu">with</span>(logbooks, thick<span class="sc">+</span>height<span class="sc">+</span>breadth)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>logbooks.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(weight<span class="sc">~</span>logVolume, <span class="at">data=</span>logbooks)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">capture.output</span>(<span class="fu">summary</span>(logbooks.lm, <span class="at">digits=</span><span class="dv">2</span>))[<span class="sc">-</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>)], <span class="at">sep=</span><span class="st">'</span><span class="sc">\n</span><span class="st">'</span>)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>Coefficients<span class="sc">:</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>            Estimate Std. Error t value <span class="fu">Pr</span>(<span class="sc">&gt;</span><span class="er">|</span>t<span class="sc">|</span>)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>(Intercept)   <span class="sc">-</span><span class="fl">8.942</span>      <span class="fl">2.731</span>  <span class="sc">-</span><span class="fl">3.274</span>  <span class="fl">0.00837</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>logVolume      <span class="fl">1.696</span>      <span class="fl">0.305</span>   <span class="fl">5.562</span>  <span class="fl">0.00024</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>Residual standard error<span class="sc">:</span> <span class="fl">0.2228</span> on <span class="dv">10</span> degrees of freedom</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>Multiple R<span class="sc">-</span>squared<span class="sc">:</span>  <span class="fl">0.7557</span>,    Adjusted R<span class="sc">-</span>squared<span class="sc">:</span>  <span class="fl">0.7313</span> </span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>F<span class="sc">-</span>statistic<span class="sc">:</span> <span class="fl">30.94</span> on <span class="dv">1</span> and <span class="dv">10</span> DF,  p<span class="sc">-</span>value<span class="sc">:</span> <span class="fl">0.00024</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The model still does relatively well on the data used. Note however that the coefficient of <code>logVolume</code> differs from the expected 1.0 by 2.28 standard errors.</p>
<p>Figure @ref(fig:fig25) made it clear that all three variables are highly correlated. We now try adding each one in turn to the model regressed <span class="math inline">\(\log(\mbox{weight})\)</span> on <span class="math inline">\(\mbox{logVolume}\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">add1</span>(logbooks.lm, <span class="at">scope=</span><span class="sc">~</span>.<span class="sc">+</span>thick<span class="sc">+</span>height<span class="sc">+</span>breadth, <span class="at">test=</span><span class="st">'F'</span>), <span class="at">digits=</span><span class="dv">4</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>Single term additions</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>Model<span class="sc">:</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>weight <span class="sc">~</span> logVolume</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>        Df Sum of Sq    RSS    AIC F value  <span class="fu">Pr</span>(<span class="sc">&gt;</span>F)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="sc">&lt;</span>none<span class="sc">&gt;</span>               <span class="fl">0.4966</span> <span class="sc">-</span><span class="fl">34.22</span>                </span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>thick    <span class="dv">1</span>    <span class="fl">0.2739</span> <span class="fl">0.2227</span> <span class="sc">-</span><span class="fl">41.84</span>  <span class="fl">11.072</span> <span class="fl">0.00884</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>height   <span class="dv">1</span>    <span class="fl">0.2437</span> <span class="fl">0.2528</span> <span class="sc">-</span><span class="fl">40.32</span>   <span class="fl">8.677</span> <span class="fl">0.01634</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>breadth  <span class="dv">1</span>    <span class="fl">0.2872</span> <span class="fl">0.2094</span> <span class="sc">-</span><span class="fl">42.58</span>  <span class="fl">12.347</span> <span class="fl">0.00658</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">add1</span>(logbooks.lm, <span class="at">scope=</span><span class="sc">~</span>.<span class="sc">+</span>thick<span class="sc">+</span>height<span class="sc">+</span>breadth, <span class="at">test=</span><span class="st">'F'</span>), <span class="at">digits=</span><span class="dv">3</span>)</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>Single term additions</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>Model<span class="sc">:</span></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>weight <span class="sc">~</span> logVolume</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>        Df Sum of Sq   RSS   AIC F value <span class="fu">Pr</span>(<span class="sc">&gt;</span>F)</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a><span class="sc">&lt;</span>none<span class="sc">&gt;</span>               <span class="fl">0.497</span> <span class="sc">-</span><span class="fl">34.2</span>               </span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>thick    <span class="dv">1</span>     <span class="fl">0.274</span> <span class="fl">0.223</span> <span class="sc">-</span><span class="fl">41.8</span>   <span class="fl">11.07</span> <span class="fl">0.0088</span></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>height   <span class="dv">1</span>     <span class="fl">0.244</span> <span class="fl">0.253</span> <span class="sc">-</span><span class="fl">40.3</span>    <span class="fl">8.68</span> <span class="fl">0.0163</span></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>breadth  <span class="dv">1</span>     <span class="fl">0.287</span> <span class="fl">0.209</span> <span class="sc">-</span><span class="fl">42.6</span>   <span class="fl">12.35</span> <span class="fl">0.0066</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The smallest value of the AIC statistic is preferred, though given the small degrees of freedom for the residual, not too much can be made of the magnitude of the reduction in AIC. The preferred model (which is also the model that gives the smallest <code>Pr(&gt;F)</code>) is then:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>addBreadth.lm <span class="ot">&lt;-</span> <span class="fu">update</span>(logbooks.lm, <span class="at">formula=</span>.<span class="sc">~</span>.<span class="sc">+</span>breadth)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">capture.output</span>(<span class="fu">summary</span>(addBreadth.lm, <span class="at">digits=</span><span class="dv">2</span>))[<span class="sc">-</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>)], <span class="at">sep=</span><span class="st">'</span><span class="sc">\n</span><span class="st">'</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>Coefficients<span class="sc">:</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>            Estimate Std. Error t value <span class="fu">Pr</span>(<span class="sc">&gt;</span><span class="er">|</span>t<span class="sc">|</span>)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>(Intercept)  <span class="sc">-</span><span class="fl">0.9192</span>     <span class="fl">2.9508</span>  <span class="sc">-</span><span class="fl">0.311</span>  <span class="fl">0.76252</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>logVolume     <span class="fl">0.4564</span>     <span class="fl">0.4100</span>   <span class="fl">1.113</span>  <span class="fl">0.29452</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>breadth       <span class="fl">1.1562</span>     <span class="fl">0.3291</span>   <span class="fl">3.514</span>  <span class="fl">0.00658</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>Residual standard error<span class="sc">:</span> <span class="fl">0.1525</span> on <span class="dv">9</span> degrees of freedom</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>Multiple R<span class="sc">-</span>squared<span class="sc">:</span>  <span class="fl">0.897</span>, Adjusted R<span class="sc">-</span>squared<span class="sc">:</span>  <span class="fl">0.8741</span> </span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>F<span class="sc">-</span>statistic<span class="sc">:</span> <span class="fl">39.19</span> on <span class="dv">2</span> and <span class="dv">9</span> DF,  p<span class="sc">-</span>value<span class="sc">:</span> <span class="fl">3.611e-05</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once account has been taken of <code>breadth</code>, <code>volume</code> does not make any clearly useful contribution to predicting <code>weight</code>. This is a result that has no, or very limited, applicability outside of the circumstances that generated this dataset.</p>
</section>
</section>
<section id="polynomial-and-spline-regression" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="polynomial-and-spline-regression"><span class="header-section-number">3.4</span> Polynomial and Spline Regression</h2>
<p>Linear regression is linear in the explanatory terms that are supplied. These can include, for example polynomial terms. Note that polynomial curves of high degree are in general unsatisfactory. Spline curves, constructed by joining low order polynomial curves (typically cubics) in such a way that the slope changes smoothly, are in general preferable.</p>
<p>The data frame <code>DAAG::seedrates</code> gives, for each of a number of different seeding rates, the number of barley grain per head.</p>
<div class="cell">

</div>
<div class="cell" data-fig.asp="1.1">
<div class="cell-output-display">
<div id="fig-fig27" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="reg_files/figure-html/fig-fig27-1.png" class="img-fluid figure-img" style="width:40.0%"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;3.6: Number of grain per head versus seeding rate, for the barley seeding rate data, with fitted quadratic curve.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Code is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(grain <span class="sc">~</span> rate, <span class="at">data=</span>DAAG<span class="sc">::</span>seedrates)   <span class="co"># Plot the data</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>seedrates.lm2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(grain <span class="sc">~</span> rate<span class="sc">+</span><span class="fu">I</span>(rate<span class="sc">^</span><span class="dv">2</span>), <span class="at">data=</span>DAAG<span class="sc">::</span>seedrates)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(<span class="at">data=</span>DAAG<span class="sc">::</span>seedrates, <span class="fu">lines</span>(<span class="fu">lowess</span>(rate, <span class="fu">fitted</span>(seedrates.lm2))))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="spline-terms-in-linear-models" class="level3" data-number="3.4.1">
<h3 data-number="3.4.1" class="anchored" data-anchor-id="spline-terms-in-linear-models"><span class="header-section-number">3.4.1</span> Spline Terms in Linear Models</h3>
<p>The fitting of polynomial functions was a simple example of the use of linear models to fit terms that may be nonlinear functions of one or more of the variables. Spline functions variables extend this idea further. The splines considered here are constructed by joining together cubic curves, in such a way the joins are smooth. The places where the cubics join are known as `knots’. It turns out that, once the knots are fixed, and depending on the class of spline curves that are used, spline functions of a variable can be constructed as linear combinations of basis functions, where each basis function is a transformation of the variable.</p>
<p>The dataset <code>cars</code>, from the _datasets+ package, gives stopping distance (<code>dist</code>, in ft) versus <code>speed</code> (mph), for cars in the 1920s.</p>
<div class="cell">

</div>
<div class="cell" data-fig.asp="0.55">
<pre><code>Loading required package: nlme
This is mgcv 1.9-0. For overview type 'help("mgcv-package")'.</code></pre>
<div class="cell-output-display">
<div id="fig-fig26" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="reg_files/figure-html/fig-fig26-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;3.7: Stopping distance (<code>dist</code>) versus <code>speed</code>, for cars from the 1920s.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Code is</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mgcv)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>cars3.gam <span class="ot">&lt;-</span> <span class="fu">gam</span>(dist <span class="sc">~</span> <span class="fu">s</span>(speed, <span class="at">k=</span><span class="dv">3</span>, <span class="at">fx=</span>T, <span class="at">bs=</span><span class="st">"cr"</span>), <span class="at">data=</span>cars)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># k=3 includes 1 degree of freedom for the intercept.</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cars3.gam, <span class="at">residuals=</span>T, <span class="at">pch=</span><span class="dv">1</span>, <span class="at">shift=</span><span class="fu">mean</span>(<span class="fu">predict</span>(cars3.gam)),</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">"Stopping distance"</span>)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="fu">title</span>(<span class="at">main=</span><span class="st">"A: Regression spline smooth -- 3 df"</span>)</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="do">## Fit with automatic choice of smoothing parameter</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>cars.gam <span class="ot">&lt;-</span> <span class="fu">gam</span>(dist <span class="sc">~</span> <span class="fu">s</span>(speed, <span class="at">k=</span><span class="dv">10</span>), <span class="at">data=</span>cars)  <span class="co"># k=10 is default</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cars.gam, <span class="at">residuals=</span>T, <span class="at">pch=</span><span class="dv">1</span>, <span class="at">shift=</span><span class="fu">mean</span>(<span class="fu">predict</span>(cars.gam)),</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">shade=</span>T)</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(cars<span class="sc">$</span>speed, <span class="fu">fitted</span>(cars3.gam), <span class="at">col=</span><span class="st">'red'</span>, <span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a><span class="fu">title</span>(<span class="at">main=</span><span class="st">"B: Penalized spline smooth"</span>)</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">'topleft'</span>, <span class="at">lty=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">'red'</span>, <span class="at">legend=</span><span class="st">"Regression spline fit from Panel A"</span>, <span class="at">bty=</span><span class="st">"n"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The Panel A choice of 3 degrees of freedom for a regression spline smooth is ad hoc. Better than such an ad hoc smooth is the penalized spline approach, which adds a penalty term that reflects model complexity to the residual sum of squares that is to&nbsp;be minimized. The name GAM (Generalized Additive Model) is used to refer to both types of model.</p>
<p>The Panel A regression spline smooth could alternatively be fitted as an <code>lm</code> style linear model. Fitting using the function <code>mgcv::gam()</code>, and specifying <code>k=3</code> and <code>fx=T</code> to obtain a regression spline fixed degrees of freedom fit, has the advantage that the function <code>plot.gam()</code> can then be used to obtain a graph that shows 2 standard error bounds.</p>
</section>
</section>
<section id="sec-lines2" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="sec-lines2"><span class="header-section-number">3.5</span> Using Factors in R Models</h2>
<p>Factors are crucial for specifying R models that include categorical or <em>factor</em> variables. Consider data from an experiment that compared houses with and without cavity insulation . While one would not usually handle these calculations using an lm model, it makes a simple example to illustrate the choi,ce of a baseline level, and a set of contrasts. Different choices, although they fit equivalent models, give output in which some of the numbers are different and must be interpreted differently.</p>
<p>We begin by entering the data from the command line:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>insulation <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"without"</span>, <span class="dv">8</span>), <span class="fu">rep</span>(<span class="st">"with"</span>, <span class="dv">7</span>)))</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 8 without, then 7 with</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>        <span class="co"># `with’ precedes `without’ in alphanumeric order, &amp; is the baseline</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>kWh <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">10225</span>, <span class="dv">10689</span>, <span class="dv">14683</span>, <span class="dv">6584</span>, <span class="dv">8541</span>, <span class="dv">12086</span>, <span class="dv">12467</span>, </span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>    <span class="dv">12669</span>, <span class="dv">9708</span>, <span class="dv">6700</span>, <span class="dv">4307</span>, <span class="dv">10315</span>, <span class="dv">8017</span>, <span class="dv">8162</span>, <span class="dv">8022</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To formulate this as a regression model, we take kWh as the dependent variable, and the factor insulation as the explanatory variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>insulation <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"without"</span>, <span class="dv">8</span>), <span class="fu">rep</span>(<span class="st">"with"</span>, <span class="dv">7</span>)))</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 8 without, then 7 with</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>kWh <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">10225</span>, <span class="dv">10689</span>, <span class="dv">14683</span>, <span class="dv">6584</span>, <span class="dv">8541</span>, <span class="dv">12086</span>, <span class="dv">12467</span>, </span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>         <span class="dv">12669</span>, <span class="dv">9708</span>, <span class="dv">6700</span>, <span class="dv">4307</span>, <span class="dv">10315</span>, <span class="dv">8017</span>, <span class="dv">8162</span>, <span class="dv">8022</span>)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>insulation.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(kWh <span class="sc">~</span> insulation)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(insulation.lm, <span class="at">corr=</span>F)</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>Call<span class="sc">:</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(<span class="at">formula =</span> kWh <span class="sc">~</span> insulation)</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>Residuals<span class="sc">:</span></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>    Min      1Q  Median      3Q     Max </span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">4409.0</span>  <span class="sc">-</span><span class="fl">979.1</span>   <span class="fl">131.9</span>  <span class="fl">1575.0</span>  <span class="fl">3690.0</span> </span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>Coefficients<span class="sc">:</span></span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>                  Estimate Std. Error t value <span class="fu">Pr</span>(<span class="sc">&gt;</span><span class="er">|</span>t<span class="sc">|</span>)</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>(Intercept)         <span class="fl">7890.1</span>      <span class="fl">873.8</span>   <span class="fl">9.030</span>  <span class="fl">5.8e-07</span></span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>insulationwithout   <span class="fl">3102.9</span>     <span class="fl">1196.4</span>   <span class="fl">2.593</span>   <span class="fl">0.0223</span></span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>Residual standard error<span class="sc">:</span> <span class="dv">2312</span> on <span class="dv">13</span> degrees of freedom</span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a>Multiple R<span class="sc">-</span>squared<span class="sc">:</span>  <span class="fl">0.341</span>, Adjusted R<span class="sc">-</span>squared<span class="sc">:</span>  <span class="fl">0.2903</span> </span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a>F<span class="sc">-</span>statistic<span class="sc">:</span> <span class="fl">6.726</span> on <span class="dv">1</span> and <span class="dv">13</span> DF,  p<span class="sc">-</span>value<span class="sc">:</span> <span class="fl">0.02228</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <span class="math inline">\(p\)</span>-value is 0.022, which may be taken as weak evidence that we can distinguish between the two types of houses. The factor levels are by default taken in alphabetical order, with the initial level as the baseline. Thus, <code>with</code> comes before <code>without</code>, and is the baseline. Hence:</p>
<p>Average for Insulated Houses = 7980<br>
Estimate for uninsulated houses = 7980 + 3103 = 10993<br>
Standard error of difference = 1196.</p>
<p>It often helps to keep in mind the model matrix or X matrix.<br>
Here are the X and the y that are used for the calculations.<br>
Note that the first eight data values were all withouts:</p>
<table class="table">
<thead>
<tr class="header">
<th>7980</th>
<th>3103</th>
<th>Add to get</th>
<th>Compare with</th>
<th>Residual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>1</td>
<td>7980+3103=10993</td>
<td>10225</td>
<td>10225-10993</td>
</tr>
<tr class="even">
<td>1</td>
<td>1</td>
<td>7980+3103=10993</td>
<td>10689</td>
<td>10689-10993</td>
</tr>
<tr class="odd">
<td>. . .</td>
<td>. . .</td>
<td>. . .</td>
<td>. . .</td>
<td>. . . .</td>
</tr>
<tr class="even">
<td>1</td>
<td>0</td>
<td>7980+0</td>
<td>9708</td>
<td>9708-7980</td>
</tr>
<tr class="odd">
<td>1</td>
<td>0</td>
<td>7980+0</td>
<td>6700</td>
<td>6700-7980</td>
</tr>
</tbody>
</table>
<p>Type</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">model.matrix</span>(kWh <span class="sc">~</span> insulation)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>   (Intercept) insulationwithout</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span>            <span class="dv">1</span>                 <span class="dv">1</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span>            <span class="dv">1</span>                 <span class="dv">1</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="dv">3</span>            <span class="dv">1</span>                 <span class="dv">1</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="dv">4</span>            <span class="dv">1</span>                 <span class="dv">1</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="dv">5</span>            <span class="dv">1</span>                 <span class="dv">1</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="dv">6</span>            <span class="dv">1</span>                 <span class="dv">1</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="dv">7</span>            <span class="dv">1</span>                 <span class="dv">1</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="dv">8</span>            <span class="dv">1</span>                 <span class="dv">1</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a><span class="dv">9</span>            <span class="dv">1</span>                 <span class="dv">0</span></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a><span class="dv">10</span>           <span class="dv">1</span>                 <span class="dv">0</span></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="dv">11</span>           <span class="dv">1</span>                 <span class="dv">0</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a><span class="dv">12</span>           <span class="dv">1</span>                 <span class="dv">0</span></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a><span class="dv">13</span>           <span class="dv">1</span>                 <span class="dv">0</span></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a><span class="dv">14</span>           <span class="dv">1</span>                 <span class="dv">0</span></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a><span class="dv">15</span>           <span class="dv">1</span>                 <span class="dv">0</span></span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a><span class="fu">attr</span>(,<span class="st">"assign"</span>)</span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>[<span class="dv">1</span>] <span class="dv">0</span> <span class="dv">1</span></span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a><span class="fu">attr</span>(,<span class="st">"contrasts"</span>)</span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a><span class="fu">attr</span>(,<span class="st">"contrasts"</span>)<span class="sc">$</span>insulation</span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>[<span class="dv">1</span>] <span class="st">"contr.treatment"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>and check that it gives the above model matrix.</p>
<section id="other-choices-of-contrasts" class="level3" data-number="3.5.1">
<h3 data-number="3.5.1" class="anchored" data-anchor-id="other-choices-of-contrasts"><span class="header-section-number">3.5.1</span> Other Choices of Contrasts</h3>
<p>There are other ways to set up the X matrix that use other choices of contrasts. One obvious alternative is to make without the first factor level, so that it becomes the baseline. For this, specify:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>insulation <span class="ot">&lt;-</span> <span class="fu">relevel</span>(insulation, <span class="at">ref=</span><span class="st">"without"</span>)      </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Make `without’ the baseline</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Another possibility is to use what are called the <code>sum</code> contrasts.<br>
With the <code>sum</code> contrasts the baseline is the mean over all factor levels. The effect for the first level is omitted; the user has to calculate it as minus the sum of the remaining effects. Here is the output from use of the `sum’ contrasts :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">contrasts =</span> <span class="fu">c</span>(<span class="st">"contr.sum"</span>, <span class="st">"contr.poly"</span>), <span class="at">digits =</span> <span class="dv">2</span>)    </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>   <span class="co">#  Try the `sum’ contrasts</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>insulation <span class="ot">&lt;-</span> <span class="fu">factor</span>(insulation, <span class="at">levels=</span><span class="fu">c</span>(<span class="st">"without"</span>, <span class="st">"with"</span>)) </span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>insulation.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(kWh <span class="sc">~</span> insulation)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(insulation.lm, <span class="at">corr=</span>F)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>Call<span class="sc">:</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(<span class="at">formula =</span> kWh <span class="sc">~</span> insulation)</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>Residuals<span class="sc">:</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>   Min     1Q Median     3Q    Max </span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a> <span class="sc">-</span><span class="dv">4409</span>   <span class="sc">-</span><span class="dv">979</span>    <span class="dv">132</span>   <span class="dv">1575</span>   <span class="dv">3690</span> </span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>Coefficients<span class="sc">:</span></span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>            Estimate Std. Error t value <span class="fu">Pr</span>(<span class="sc">&gt;</span><span class="er">|</span>t<span class="sc">|</span>)</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>(Intercept)     <span class="dv">9442</span>        <span class="dv">598</span>   <span class="fl">15.78</span>  <span class="fl">7.4e-10</span></span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>insulation1     <span class="dv">1551</span>        <span class="dv">598</span>    <span class="fl">2.59</span>    <span class="fl">0.022</span></span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a>Residual standard error<span class="sc">:</span> <span class="dv">2310</span> on <span class="dv">13</span> degrees of freedom</span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a>Multiple R<span class="sc">-</span>squared<span class="sc">:</span>  <span class="fl">0.341</span>, Adjusted R<span class="sc">-</span>squared<span class="sc">:</span>  <span class="fl">0.29</span> </span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a>F<span class="sc">-</span>statistic<span class="sc">:</span> <span class="fl">6.73</span> on <span class="dv">1</span> and <span class="dv">13</span> DF,  p<span class="sc">-</span>value<span class="sc">:</span> <span class="fl">0.0223</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here is the interpretation:</p>
<p>Average of (mean for “without”, “mean for with”) = 9442<br>
Estimate for uninsulated houses (the first level) = 9442 + 1551 = 10993 As <em>effects</em> sum to one, the effect for the 2<span class="math inline">\(^{nd}\)</span> level (`with’) is -1551.<br>
Thus the estimate for insulated houses (1<span class="math inline">\(^{st}\)</span> level) = 9442 - 1551 = 7980.</p>
<p>The sum contrasts are sometimes called “analysis of variance” contrasts. It is possible to set the choice of contrasts for each factor separately, with a statement such as:</p>
<pre><code>insulation &lt;- C(insulation, contr=treatment)</code></pre>
<p>Also available are the helmert contrasts. These are not at all intuitive and rarely helpful, even though S-PLUS uses them as the default. Novices should avoid them .</p>
</section>
</section>
<section id="multiple-lines-different-regression-lines-for-different-species" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="multiple-lines-different-regression-lines-for-different-species"><span class="header-section-number">3.6</span> Multiple Lines – Different Regression Lines for Different Species</h2>
<p>The terms that appear on the right of the model formula may be variables or factors, or interactions between variables and factors, or interactions between factors. Here we take advantage of this to fit different lines to different subsets of the data.</p>
<p>In the example that follows, we have weights for a porpoise species (Stellena styx) and for a dolphin species (Delphinus delphis).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>dolphins <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">weight =</span> <span class="fu">c</span>(<span class="dv">35</span>, <span class="dv">42</span>, <span class="dv">71</span>, <span class="dv">65</span>, <span class="dv">63</span>, <span class="dv">64</span>, <span class="dv">45</span>, <span class="dv">54</span>, <span class="dv">59</span>, <span class="dv">50</span>, </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="dv">42</span>, <span class="dv">55</span>, <span class="dv">37</span>, <span class="dv">47</span>, <span class="dv">40</span>, <span class="dv">52</span>), </span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">heart =</span> <span class="fu">c</span>(<span class="dv">245</span>, <span class="dv">255</span>, <span class="dv">525</span>, <span class="dv">425</span>, <span class="dv">425</span>, <span class="dv">440</span>, </span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="dv">350</span>, <span class="dv">300</span>, <span class="dv">350</span>, <span class="dv">320</span>, <span class="dv">240</span>, <span class="dv">305</span>, <span class="dv">220</span>, <span class="dv">310</span>, <span class="dv">210</span>, <span class="dv">350</span>),</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="at">species =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"styx"</span>, <span class="st">"delph"</span>), <span class="fu">c</span>(<span class="dv">7</span>,<span class="dv">9</span>))</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">

</div>
<p><a href="#fig-fig28">Figure&nbsp;<span>3.8</span></a> shows a plot of the data, with separate lines fitted for the two species:</p>
<div class="cell" data-fig.asp="1">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lattice)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">xyplot</span>(heart <span class="sc">~</span> weight, <span class="at">groups=</span>species, <span class="at">auto.key=</span><span class="fu">list</span>(<span class="at">columns=</span><span class="dv">2</span>), <span class="at">data=</span>dolphins,</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">par.settings=</span><span class="fu">simpleTheme</span>(<span class="at">pch=</span><span class="fu">c</span>(<span class="dv">16</span>,<span class="dv">17</span>)), <span class="at">type=</span><span class="fu">c</span>(<span class="st">"p"</span>,<span class="st">"r"</span>), <span class="at">scales=</span><span class="fu">list</span>(<span class="at">log=</span>T))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-fig28" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="reg_files/figure-html/fig-fig28-1.png" class="img-fluid figure-img" style="width:40.0%"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;3.8: Height weight versus body weight, with lobgarithmic scales on both axes. Separate lines are fitted for the two dolphin species.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>We take <code>x1</code> to be a variable that has the value 0 for Delphinus delphis, and 1 for Stellena styx. We take <code>x2</code> to be body weight. Possibilities we may want to consider are:</p>
<ol type="a">
<li>A single line: <code>y = a + b x2</code><br>
</li>
<li>Two parallel lines: <code>y = a1 + a2 x1 + b x2</code><br>
[For the first group (Stellena styx; <code>x1</code> = 0) the constant term is <code>a1</code>, while for the second group (Delphinus delphis; <code>x1</code> = 1) the constant term is <code>a1 + a2</code>.]<br>
</li>
<li>Two separate lines: <code>y = a1 + a2 x1 + b1 x2  + b2 x1 x2</code><br>
[For the first group (Delphinus delphis; <code>x1</code> = 0) the constant term is <code>a1</code> and the slope is <code>b1</code>. For the second group (Stellena styx; <code>x1</code> = 1) the constant term is <code>a1 + a2</code>, and the slope is <code>b1 + b2</code>.]</li>
</ol>
<p>Now compare these three models, both with the AIC statistics, and with AICc which adjusts for small sample size. AIC is one of several alternative ‘information’ statistics.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>cet.lm1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(heart) <span class="sc">~</span> <span class="fu">log</span>(weight), <span class="at">data =</span> dolphins)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>cet.lm2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(heart) <span class="sc">~</span> <span class="fu">factor</span>(species) <span class="sc">+</span> <span class="fu">log</span>(weight), <span class="at">data =</span> dolphins)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>cet.lm3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(heart) <span class="sc">~</span> <span class="fu">factor</span>(species) <span class="sc">+</span> <span class="fu">factor</span>(species)<span class="sc">/</span><span class="fu">log</span>(weight), <span class="at">data =</span> dolphins)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="fu">AIC</span>(cet.lm1, cet.lm2, cet.lm3), </span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">AICc =</span> <span class="fu">sapply</span>(<span class="fu">list</span>(cet.lm1, cet.lm2, cet.lm3), AICcmodavg<span class="sc">::</span>AICc))</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>        df AIC AICc</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>cet.lm1  <span class="dv">3</span> <span class="sc">-</span><span class="dv">21</span>  <span class="sc">-</span><span class="dv">19</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>cet.lm2  <span class="dv">4</span> <span class="sc">-</span><span class="dv">28</span>  <span class="sc">-</span><span class="dv">25</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>cet.lm3  <span class="dv">5</span> <span class="sc">-</span><span class="dv">27</span>  <span class="sc">-</span><span class="dv">21</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The smallest value is best, in both cases. Both statistics favour the parallel lines model. The AICc statistic makes a much clearer case against fitting separate lines.</p>
<p>Selected rows of the model matrix are:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">model.matrix</span>(cet.lm2)[<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">8</span>,<span class="dv">16</span>), ]</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>   (Intercept) <span class="fu">factor</span>(species)<span class="dv">1</span> <span class="fu">log</span>(weight)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span>            <span class="dv">1</span>               <span class="sc">-</span><span class="dv">1</span>         <span class="fl">3.6</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span>            <span class="dv">1</span>               <span class="sc">-</span><span class="dv">1</span>         <span class="fl">3.7</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="dv">8</span>            <span class="dv">1</span>                <span class="dv">1</span>         <span class="fl">4.0</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="dv">16</span>           <span class="dv">1</span>                <span class="dv">1</span>         <span class="fl">4.0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now try an analysis of variance comparison.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>cet.lm3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(heart) <span class="sc">~</span> <span class="fu">factor</span>(species) <span class="sc">+</span> <span class="fu">log</span>(weight) <span class="sc">+</span> </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">factor</span>(species)<span class="sc">:</span><span class="fu">log</span>(weight), <span class="at">data=</span>dolphins)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(cet.lm1,cet.lm2,cet.lm3) </span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>Analysis of Variance Table</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>Model <span class="dv">1</span><span class="sc">:</span> <span class="fu">log</span>(heart) <span class="sc">~</span> <span class="fu">log</span>(weight)</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>Model <span class="dv">2</span><span class="sc">:</span> <span class="fu">log</span>(heart) <span class="sc">~</span> <span class="fu">factor</span>(species) <span class="sc">+</span> <span class="fu">log</span>(weight)</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>Model <span class="dv">3</span><span class="sc">:</span> <span class="fu">log</span>(heart) <span class="sc">~</span> <span class="fu">factor</span>(species) <span class="sc">+</span> <span class="fu">log</span>(weight) <span class="sc">+</span> <span class="fu">factor</span>(species)<span class="sc">:</span><span class="fu">log</span>(weight)</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>  Res.Df    RSS Df Sum of Sq    F <span class="fu">Pr</span>(<span class="sc">&gt;</span>F)</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span>     <span class="dv">14</span> <span class="fl">0.1717</span>                         </span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span>     <span class="dv">13</span> <span class="fl">0.0959</span>  <span class="dv">1</span>    <span class="fl">0.0758</span> <span class="fl">9.59</span> <span class="fl">0.0093</span></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a><span class="dv">3</span>     <span class="dv">12</span> <span class="fl">0.0949</span>  <span class="dv">1</span>    <span class="fl">0.0010</span> <span class="fl">0.12</span> <span class="fl">0.7346</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="aov-models-analysis-of-variance" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="aov-models-analysis-of-variance"><span class="header-section-number">3.7</span> aov models (Analysis of Variance)</h2>
<p>The class of models that can be directly fitted as aov models is quite limited. In essence, <code>aov()</code> provides, for data where all combinations of factor levels have the same number of observations, another view of an lm model. One can however specify the error term that is to be used in testing for treatment effects. See <a href="#sec-errorAOV"><span>Section&nbsp;3.8</span></a> below.</p>
<p>By default, R uses the treatment contrasts for factors, i.e.&nbsp;the first level is taken as the baseline or reference level. A useful function is <code>relevel()</code>, using the parameter <code>ref</code> to set the level that is wanted as the reference level.</p>
<section id="plant-growth-example" class="level3" data-number="3.7.1">
<h3 data-number="3.7.1" class="anchored" data-anchor-id="plant-growth-example"><span class="header-section-number">3.7.1</span> Plant Growth Example</h3>
<p><a href="#fig-fig29">Figure&nbsp;<span>3.9</span></a> shows boxplot comparisons of plant weight.</p>
<div class="cell">

</div>
<div class="cell" data-fig.asp="0.4">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>opar <span class="ot">&lt;-</span> <span class="fu">par</span>(<span class="at">mgp=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="fl">0.5</span>,<span class="dv">0</span>), <span class="at">mar=</span><span class="fu">c</span>(<span class="fl">3.6</span>,<span class="fl">3.1</span>,<span class="fl">2.1</span>,<span class="fl">0.6</span>))</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(PlantGrowth, <span class="fu">boxplot</span>(<span class="fu">split</span>(weight, group), <span class="at">horizontal=</span>T))</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(opar)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-fig29" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="reg_files/figure-html/fig-fig29-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;3.9: Boxplots of plant weight, by group</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Now fit a model using <code>aov()</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>PlantGrowth.aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(weight<span class="sc">~</span>group, <span class="at">data=</span>PlantGrowth)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(PlantGrowth.aov)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>            Df Sum Sq Mean Sq F value <span class="fu">Pr</span>(<span class="sc">&gt;</span>F)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>group        <span class="dv">2</span>   <span class="fl">3.77</span>   <span class="fl">1.883</span>    <span class="fl">4.85</span>  <span class="fl">0.016</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>Residuals   <span class="dv">27</span>  <span class="fl">10.49</span>   <span class="fl">0.389</span>               </span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary.lm</span>(PlantGrowth.aov)   <span class="co"># As from `lm` model fit</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>Call<span class="sc">:</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a><span class="fu">aov</span>(<span class="at">formula =</span> weight <span class="sc">~</span> group, <span class="at">data =</span> PlantGrowth)</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>Residuals<span class="sc">:</span></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>   Min     1Q Median     3Q    Max </span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">1.071</span> <span class="sc">-</span><span class="fl">0.418</span> <span class="sc">-</span><span class="fl">0.006</span>  <span class="fl">0.263</span>  <span class="fl">1.369</span> </span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>Coefficients<span class="sc">:</span></span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>            Estimate Std. Error t value <span class="fu">Pr</span>(<span class="sc">&gt;</span><span class="er">|</span>t<span class="sc">|</span>)</span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a>(Intercept)    <span class="fl">5.073</span>      <span class="fl">0.114</span>   <span class="fl">44.57</span>   <span class="sc">&lt;</span><span class="fl">2e-16</span></span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a>group1        <span class="sc">-</span><span class="fl">0.041</span>      <span class="fl">0.161</span>   <span class="sc">-</span><span class="fl">0.25</span>    <span class="fl">0.801</span></span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a>group2        <span class="sc">-</span><span class="fl">0.412</span>      <span class="fl">0.161</span>   <span class="sc">-</span><span class="fl">2.56</span>    <span class="fl">0.016</span></span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-21"><a href="#cb39-21" aria-hidden="true" tabindex="-1"></a>Residual standard error<span class="sc">:</span> <span class="fl">0.62</span> on <span class="dv">27</span> degrees of freedom</span>
<span id="cb39-22"><a href="#cb39-22" aria-hidden="true" tabindex="-1"></a>Multiple R<span class="sc">-</span>squared<span class="sc">:</span>  <span class="fl">0.264</span>, Adjusted R<span class="sc">-</span>squared<span class="sc">:</span>  <span class="fl">0.21</span> </span>
<span id="cb39-23"><a href="#cb39-23" aria-hidden="true" tabindex="-1"></a>F<span class="sc">-</span>statistic<span class="sc">:</span> <span class="fl">4.85</span> on <span class="dv">2</span> and <span class="dv">27</span> DF,  p<span class="sc">-</span>value<span class="sc">:</span> <span class="fl">0.0159</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="dataset-masscabbages-run-code-to-get-output" class="level3" data-number="3.7.2">
<h3 data-number="3.7.2" class="anchored" data-anchor-id="dataset-masscabbages-run-code-to-get-output"><span class="header-section-number">3.7.2</span> Dataset <code>MASS::cabbages</code> (Run code to get output)</h3>
<p>Type <code>?MASS::cabbages</code> to get details of the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">help</span>(cabbages)         <span class="co"># cabbages is from the MASS package</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(cabbages)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">coplot</span>(HeadWt<span class="sc">~</span>VitC<span class="sc">|</span>Cult<span class="sc">+</span>Date,<span class="at">data=</span>cabbages)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Examination of the plot suggests that cultivars differ greatly in the variability in head weight. Variation in the vitamin C levels seems relatively consistent between cultivars.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>VitC.aov<span class="ot">&lt;-</span><span class="fu">aov</span>(VitC<span class="sc">~</span>Cult<span class="sc">+</span>Date,<span class="at">data=</span>cabbages)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(VitC.aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="sec-errorAOV" class="level2" data-number="3.8">
<h2 data-number="3.8" class="anchored" data-anchor-id="sec-errorAOV"><span class="header-section-number">3.8</span> Shading of Kiwifruit Vines</h2>
<p>These data (yields in kilograms) in the data frame <code>DAAG::kiwishade</code>, are from an experiment where there were four treatments - no shading, shading from August to December, shading from December to February, and shading from February to May. Each treatment appeared once in each of the three blocks. The northernmost plots were grouped in one block because they were similarly affected by shading from the sun. For the remaining two blocks shelter effects, in one case from the east and in the other case from the west, were thought more important. Results are given for each of the four vines in each plot. In experimental design parlance, the four vines within a plot constitute subplots.</p>
<p>The <code>block:shade</code> mean square (sum of squares divided by degrees of freedom) provides the error term. (If this is not specified, one still gets a correct analysis of variance breakdown. But the <span class="math inline">\(F\)</span>-statistics and <span class="math inline">\(p\)</span>-values will be wrong.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>kiwishade <span class="ot">&lt;-</span> DAAG<span class="sc">::</span>kiwishade</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>kiwishade<span class="sc">$</span>shade <span class="ot">&lt;-</span> <span class="fu">relevel</span>(kiwishade<span class="sc">$</span>shade, <span class="at">ref=</span><span class="st">"none"</span>)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Make sure that the level “none” (no shade) is used as reference</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>kiwishade.aov<span class="ot">&lt;-</span><span class="fu">aov</span>(yield<span class="sc">~</span>block<span class="sc">+</span>shade<span class="sc">+</span><span class="fu">Error</span>(block<span class="sc">:</span>shade),<span class="at">data=</span>kiwishade) </span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>Warning <span class="cf">in</span> <span class="fu">aov</span>(yield <span class="sc">~</span> block <span class="sc">+</span> shade <span class="sc">+</span> <span class="fu">Error</span>(block<span class="sc">:</span>shade), <span class="at">data =</span> kiwishade)<span class="sc">:</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="fu">Error</span>() model is singular</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(kiwishade.aov)</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>Error<span class="sc">:</span> block<span class="sc">:</span>shade</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>          Df Sum Sq Mean Sq F value <span class="fu">Pr</span>(<span class="sc">&gt;</span>F)</span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>block      <span class="dv">2</span>    <span class="dv">172</span>      <span class="dv">86</span>    <span class="fl">4.12</span> <span class="fl">0.0749</span></span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>shade      <span class="dv">3</span>   <span class="dv">1395</span>     <span class="dv">465</span>   <span class="fl">22.21</span> <span class="fl">0.0012</span></span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>Residuals  <span class="dv">6</span>    <span class="dv">126</span>      <span class="dv">21</span>               </span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a>Error<span class="sc">:</span> Within</span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a>          Df Sum Sq Mean Sq F value <span class="fu">Pr</span>(<span class="sc">&gt;</span>F)</span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a>Residuals <span class="dv">36</span>    <span class="dv">439</span>    <span class="fl">12.2</span>               </span>
<span id="cb42-18"><a href="#cb42-18" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(kiwishade.aov)</span>
<span id="cb42-19"><a href="#cb42-19" aria-hidden="true" tabindex="-1"></a>(Intercept) <span class="sc">:</span></span>
<span id="cb42-20"><a href="#cb42-20" aria-hidden="true" tabindex="-1"></a>(Intercept) </span>
<span id="cb42-21"><a href="#cb42-21" aria-hidden="true" tabindex="-1"></a>         <span class="dv">97</span> </span>
<span id="cb42-22"><a href="#cb42-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-23"><a href="#cb42-23" aria-hidden="true" tabindex="-1"></a>block<span class="sc">:</span>shade <span class="sc">:</span></span>
<span id="cb42-24"><a href="#cb42-24" aria-hidden="true" tabindex="-1"></a>block1 block2 shade1 shade2 shade3 </span>
<span id="cb42-25"><a href="#cb42-25" aria-hidden="true" tabindex="-1"></a>  <span class="fl">0.81</span>   <span class="fl">1.81</span>   <span class="fl">3.67</span>   <span class="fl">6.70</span>  <span class="sc">-</span><span class="fl">6.61</span> </span>
<span id="cb42-26"><a href="#cb42-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-27"><a href="#cb42-27" aria-hidden="true" tabindex="-1"></a>Within <span class="sc">:</span></span>
<span id="cb42-28"><a href="#cb42-28" aria-hidden="true" tabindex="-1"></a><span class="fu">numeric</span>(<span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exercises" class="level2" data-number="3.9">
<h2 data-number="3.9" class="anchored" data-anchor-id="exercises"><span class="header-section-number">3.9</span> Exercises</h2>
<ol type="1">
<li>The datasets <code>DAAG::elastic1</code> and <code>DAAG::elastic2</code> were both obtained using the same apparatus, including the same rubber band, as the data frame <code>DAAG::elasticband</code>. The variable <code>stretch</code> is, in each case, the amount by which an elastic band was stretched over the end of a ruler, and <code>distance</code> the distance that the band traveled when released.<br>
</li>
</ol>
<ol type="a">
<li>Using a different symbol and/or a different colour, plot the data from the two data frames <code>elastic1</code> and <code>elastic2</code> on the same graph.<br>
Do the two sets of results appear consistent?<br>
</li>
<li>For each of the data sets <code>elastic1</code> and <code>elastic2</code>, determine the regression of <code>stretch</code> on <code>distance</code>. In each case determine</li>
</ol>
<ol type="i">
<li>fitted values and standard errors of fitted values and</li>
<li>the R<span class="math inline">\(^2\)</span> statistic. Compare the two sets of results. What is the key difference?</li>
</ol>
<ol start="2" type="1">
<li>Enter the data frame beams, thus:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>beams <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">strength =</span> <span class="fu">c</span>(<span class="fl">11.14</span>, <span class="fl">12.74</span>, <span class="fl">13.13</span>, <span class="fl">11.51</span>, <span class="fl">12.38</span>, </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>               <span class="fl">12.6</span>, <span class="fl">11.13</span>, <span class="fl">11.7</span>, <span class="fl">11.02</span>, <span class="fl">11.41</span>), </span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">SpecificGravity =</span> <span class="fu">c</span>(<span class="fl">0.499</span>, <span class="fl">0.558</span>, <span class="fl">0.604</span>, <span class="fl">0.441</span>, <span class="fl">0.55</span>, </span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>                      <span class="fl">0.528</span>, <span class="fl">0.418</span>, <span class="fl">0.48</span>, <span class="fl">0.406</span>, <span class="fl">0.467</span>), </span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">moisture =</span> <span class="fu">c</span>(<span class="fl">11.1</span>, <span class="fl">8.9</span>, <span class="fl">8.8</span>, <span class="fl">8.9</span>, <span class="fl">8.8</span>, <span class="fl">9.9</span>, <span class="fl">10.7</span>, <span class="fl">10.5</span>, </span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>               <span class="fl">10.5</span>, <span class="fl">10.7</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Regress <code>strength</code> on <code>SpecificGravity</code> and <code>Moisture</code>. Carefully examine the regression diagnostic plot, obtained by supplying the name of the lm object as the first parameter to plot(). What does this indicate?</p>
<ol start="3" type="1">
<li><p>Using the data frame <code>cars</code> (in the datasets package), plot distance (i.e.&nbsp;stopping distance) versus speed. Fit a line to this relationship, and plot the line. Then try fitting and plotting a quadratic curve. Does the quadratic curve give a useful improvement to the fit? If you have studied the dynamics of particles, can you find a theory that would tell you how stopping distance might change with speed?</p></li>
<li><p>Using the data frame hills (in package MASS), regress time on distance and climb. What can you learn from the diagnostic plots that you get when you plot the lm object? Try also regressing log(time) on log(distance) and log(climb). Which of these regression equations would you prefer?</p></li>
<li><p>Use the method of <a href="#sec-lines2"><span>Section&nbsp;3.5</span></a> to determine, formally, whether one needs different regression lines for the two data frames elastic1 and elastic2.</p></li>
</ol>
<p>6.In <a href="#sec-lines2"><span>Section&nbsp;3.5</span></a>, check the form of the model matrix (i) for fitting two parallel lines and (ii) for fitting two arbitrary lines, using the sum contrasts.</p>
<ol start="7" type="1">
<li>Type</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>hosp<span class="ot">&lt;-</span><span class="fu">rep</span>(<span class="fu">c</span>(”RNC”,”Hunter”,”Mater”),<span class="dv">2</span>)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>hosp</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>fhosp<span class="ot">&lt;-</span><span class="fu">factor</span>(hosp)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(fhosp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now repeat the steps involved in forming the factor <code>fhosp</code>, this time keeping the factor levels in the order <code>"RNC"</code>, <code>"Hunter"</code>, <code>"Mater"</code>. Use <code>contrasts(fhosp)</code> to form and print out the matrix of contrasts. Do this using helmert contrasts, treatment contrasts, and sum contrasts. Using an outcome variable</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">8</span>,<span class="dv">10</span>,<span class="dv">3</span>,<span class="dv">9</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>fit the model <code>lm(y~fhosp)</code>, repeating the fit for each of the three different choices of contrasts. Comment on what you get. For which choice(s) of contrasts do the parameter estimates change when you re-order the factor levels?</p>
<ol start="8" type="1">
<li><p>In the data set <code>MASS::cement</code>, examine the dependence of <code>y</code> (amount of heat produced) on <code>x1</code>, <code>x2</code>, <code>x3</code> and <code>x4</code> (which are proportions of four constituents). Begin by examining the scatterplot matrix. As the explanatory variables are proportions, do they require transformation, perhaps by taking <code>log(x/(100-x))</code>? What alternative strategies one might use to find an effective prediction equation?</p></li>
<li><p>In the dataset <code>pressure</code> (datasets), examine the dependence of <code>pressure</code> on temperature.<br>
[Transformation of temperature makes sense only if one first converts to degrees Kelvin. Consider transformation of pressure. A logarithmic transformation is too extreme; the direction of the curvature changes. What family of transformations might one try?</p></li>
<li><p>*Repeat the analysis of the kiwishade data (section 5.8.2), but replacing Error(block:shade) with block:shade. Comment on the output that you get from summary(). To what extent is it potentially misleading? Also do the analysis where the block:shade term is omitted altogether. Comment on that analysis.</p></li>
</ol>
</section>
<section id="references-and-reading" class="level2" data-number="3.10">
<h2 data-number="3.10" class="anchored" data-anchor-id="references-and-reading"><span class="header-section-number">3.10</span> References and reading</h2>
<p><span class="citation" data-cites="cunningham2021causal">Cunningham (<a href="references.html#ref-cunningham2021causal" role="doc-biblioref">2021</a>)</span> . Causal inference. Yale University Press.</p>
<p><span class="citation" data-cites="Faraway">Faraway (<a href="references.html#ref-Faraway" role="doc-biblioref">2014</a>)</span> . Linear Models with R. Taylor &amp; Francis.</p>
<p><span class="citation" data-cites="fox2018r">Fox and Weisberg (<a href="references.html#ref-fox2018r" role="doc-biblioref">2018</a>)</span> . An R and S-PLUS Companion to Applied Regression. Sage Books.</p>
<p><span class="citation" data-cites="maindonald2010data">J. Maindonald and Braun (<a href="references.html#ref-maindonald2010data" role="doc-biblioref">2010</a>)</span> . Data Analysis and Graphics Using R –- An Example-Based Approach. Cambridge University Press.</p>
<p><span class="citation" data-cites="maindonald2023">J. Maindonald, Braun, and Andrews (<a href="references.html#ref-maindonald2023" role="doc-biblioref">2024, forthcoming</a>)</span> . A Practical Guide to Data Analysis Using R. An Example-Based Approach. Cambridge University Press.</p>
<p><span class="citation" data-cites="MainDesign">J. H. Maindonald (<a href="references.html#ref-MainDesign" role="doc-biblioref">1992</a>)</span> . Statistical design, analysis and presentation issues.</p>
<p><span class="citation" data-cites="Muenchen">Muenchen (<a href="references.html#ref-Muenchen" role="doc-biblioref">2011</a>)</span> . R for SAS and SPSS Users. Springer.</p>
<p><span class="citation" data-cites="Tu-epi">Tu and Gilthorpe (<a href="references.html#ref-Tu-epi" role="doc-biblioref">2011</a>)</span> . Statistical thinking in epidemiology. CRC Press.</p>
<p><span class="citation" data-cites="VR-MASS">Venables and Ripley (<a href="references.html#ref-VR-MASS" role="doc-biblioref">2002</a>)</span> . Modern Applied Statistics with S. Springer, NY.<br>
[This assumes a fair level of statistical sophistication.<br>
Explanation is careful, but often terse.</p>
<p><span class="citation" data-cites="Wood-2017">Wood (<a href="references.html#ref-Wood-2017" role="doc-biblioref">2017</a>)</span> . Generalized Additive Models. An Introduction with R. Chapman and Hall/CRC.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography" style="display: none">
<div id="ref-cunningham2021causal" class="csl-entry" role="doc-biblioentry">
Cunningham, Scott. 2021. <em>Causal Inference</em>. Yale University Press. <a href="https://mixtape.scunning.com/index.html">https://mixtape.scunning.com/index.html</a>.
</div>
<div id="ref-davies1947statistical" class="csl-entry" role="doc-biblioentry">
Davies, Owen L et al. 1947. <span>“Statistical Methods in Research and Production.”</span>
</div>
<div id="ref-Faraway" class="csl-entry" role="doc-biblioentry">
Faraway, Julian J. 2014. <em>Linear Models with <span>R</span></em>. 2nd ed. Taylor &amp; Francis Ltd.
</div>
<div id="ref-fox2018r" class="csl-entry" role="doc-biblioentry">
Fox, John, and Sanford Weisberg. 2018. <em>An <span>R</span> Companion to Applied Regression</em>. Sage publications. <a href="http://socserv.socsci.mcmaster.ca/jfox/Books/Companion">http://socserv.socsci.mcmaster.ca/jfox/Books/Companion</a>.
</div>
<div id="ref-MainDesign" class="csl-entry" role="doc-biblioentry">
Maindonald, J H. 1992. <span>“Statistical Design, Analysis, and Presentation Issues.”</span> <em>New Zealand Journal of Agricultural Research</em> 35 (2): 121–41.
</div>
<div id="ref-maindonald2010data" class="csl-entry" role="doc-biblioentry">
Maindonald, John, and John Braun. 2010. <em>Data Analysis and Graphics Using r: An Example-Based Approach</em>. Cambridge University Press.
</div>
<div id="ref-maindonald2023" class="csl-entry" role="doc-biblioentry">
Maindonald, John, John Braun, and Jeffrey Andrews. 2024, forthcoming. <em>A Practical Guide to Data Analysis Using r. An Example-Based Approach.</em> Cambridge University Press.
</div>
<div id="ref-Muenchen" class="csl-entry" role="doc-biblioentry">
Muenchen, R. A. 2011. <em>R for SAS and SPSS Users</em>. 2nd ed. Springer.
</div>
<div id="ref-Tu-epi" class="csl-entry" role="doc-biblioentry">
Tu, Y., and M. S. Gilthorpe. 2011. <em>Statistical Thinking in Epidemiology.</em> CRC Press.
</div>
<div id="ref-VR-MASS" class="csl-entry" role="doc-biblioentry">
Venables, W. N., and B. D. Ripley. 2002. <em>Modern Applied Statistics with <span>S</span></em>. 4th ed. Springer.
</div>
<div id="ref-Wood-2017" class="csl-entry" role="doc-biblioentry">
Wood, S. N. 2017. <em>Generalized Additive Models. An Introduction with r</em>. 2nd ed. Chapman; Hall/CRC.
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>The original source is <span class="citation" data-cites="davies1947statistical">Davies et al. (<a href="references.html#ref-davies1947statistical" role="doc-biblioref">1947</a>)</span> , Table 6.1, p.&nbsp;119.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./graphs.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Base R Graphics</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./GLMandA.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Generalized Linear and Additive Models</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>